lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-shallowmapping_logo_light.png
  - docs/
  - pyproject.toml
  - .gitignore
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/*
  - .github/CONTRIBUTING.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - conf/igenomes.config
  - conf/igenomes.config
  - conf/test.config
  - conf/test_full.config
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-shallowmapping_logo_light.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - process.cpus
  - process.memory
  - process.time
  - custom_config
repository_type: pipeline
template:
  prefix: ebi-metagenomics
  skip:
  - igenomes
  - nf_core_configs
