lint:
  nextflow_config: false
  nf_test_content: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - assets/nf-core-biosiftr_logo_light.png
    - docs/
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - docs/images/nf-core-biosiftr_logo_dark.png
    - docs/images/nf-core-biosiftr_logo_light.png
    - pyproject.toml
    - .gitignore
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/*
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - conf/igenomes.config
    - conf/igenomes.config
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowBiosiftr.groovy
    - lib/nfcore_external_java_deps.jar
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-biosiftr_logo_light.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - .gitignore
    - pyproject.toml
    - LICENSE
    - .prettierrc.yml
  actions_ci: false
  multiqc_config:
    - report_comment
repository_type: pipeline
template:
  prefix: ebi-metagenomics
  skip:
    - igenomes
    - nf_core_configs
  is_nfcore: false
