name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'ebi-metagenomics/biosiftr') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - 25.04.7
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true
          version: 0.9.2

      - name: Run the nf-test
        run: |
          nf-test test --ci --profile test,docker
